.PHONY : submit_bbh
submit_bbh : 
	bilby_pipe GW150914.ini --submit
	bilby_pipe GW151012.ini --submit
	bilby_pipe GW151226.ini --submit
	bilby_pipe GW170104.ini --submit
	bilby_pipe GW170608.ini --submit
	bilby_pipe GW170729.ini --submit
	bilby_pipe GW170809.ini --submit
	bilby_pipe GW170814.ini --submit
	bilby_pipe GW170818.ini --submit
	bilby_pipe GW170823.ini --submit
